from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager
import logging

from app.config import settings
from app.database import AsyncSessionLocal
from app.routers import auth, users, products, categories, cart, orders, admin

logger = logging.getLogger("navix.startup")


async def ensure_admin_user():
    """
    Upsert the admin user on startup so the bcrypt hash is always
    generated by the same passlib context used for verification.
    This is the fix for 'Invalid credentials' on the admin login.
    """
    from sqlalchemy import select, text
    from app.models import User
    from app.utils.auth import hash_password

    async with AsyncSessionLocal() as session:
        try:
            result = await session.execute(
                select(User).where(User.email == "admin@navix.com")
            )
            admin_user = result.scalar_one_or_none()
            fresh_hash = hash_password("Admin@1234")
            if admin_user is None:
                admin_user = User(
                    name="Navix Admin",
                    email="admin@navix.com",
                    password_hash=fresh_hash,
                    role="admin",
                )
                session.add(admin_user)
                logger.info("Admin user created on startup.")
            else:
                admin_user.password_hash = fresh_hash
                session.add(admin_user)
                logger.info("Admin user password refreshed on startup.")
            await session.commit()
        except Exception as e:
            await session.rollback()
            logger.error(f"Failed to ensure admin user: {e}")


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup — ensure admin account is valid
    await ensure_admin_user()
    yield
    # Shutdown


app = FastAPI(
    title="Navix Grocery Store API",
    description="Full-stack grocery store backend — auth, products, cart, orders, and admin",
    version="1.0.0",
    lifespan=lifespan,
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.origins_list,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Routers
app.include_router(auth.router,       prefix="/api")
app.include_router(users.router,      prefix="/api")
app.include_router(products.router,   prefix="/api")
app.include_router(categories.router, prefix="/api")
app.include_router(cart.router,       prefix="/api")
app.include_router(orders.router,     prefix="/api")
app.include_router(admin.router,      prefix="/api")


@app.get("/health", tags=["Health"])
async def health():
    return {"status": "ok", "service": "navix-api"}
